---
server:
  port: "${PORT:8081}"

spring:
  application:
    name: stock-market-data-service

eureka:
  client:
    serviceUrl:
      defaultZone: "${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/"

management:
  security:
    enabled: false

security:
  basic:
    enabled: false